export default {
    success: "success",
    selects: document.querySelectorAll('.select'),
    amountInput: document.getElementById('amount'),
    form: document.querySelector(".form"),
    formResults: document.querySelector(".form__results"),
    resultFrom: document.getElementById('resultFrom'),
    resultTo: document.getElementById('resultTo'),
    rateConversion: document.querySelector(".rate-conversion"),
    rateLast: document.querySelector(".rate-last"),
    swithButton: document.querySelector(".switch-currencies"),
    toSelect: document.getElementById('to'),
    fromSelect: document.getElementById('from'),
    tabs: document.querySelectorAll('.tab'),
    currentCurrency: document.querySelector('.currency-single__item'),
    currentCurrencyList: document.querySelector('.currency-list'),
    singleSelect: document.getElementById('singleSelect'),
    addButton: document.querySelector('.currency-add__button'),
    addCurrencySelect: document.getElementById('addCurrencySelect')
}